/**
 * Generate a self-contained service worker (no Workbox runtime dependency).
 *
 * Runs as the LAST step in the build pipeline (after astro build and
 * postprocess:reader-copy) so the precache manifest reflects the final
 * dist content.
 */
import { glob } from "node:fs/promises";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";

const DIST = "dist";
const CACHE_VERSION = Date.now().toString(36);
const EXTENSIONS = ["html", "css", "js", "json", "md", "svg", "webp", "txt", "jsonl", "png", "webmanifest"];

// Collect all files to precache (relative to dist/)
const files = [];
const globPattern = `**/*.{${EXTENSIONS.join(",")}}`;
for await (const entry of glob(globPattern, { cwd: DIST })) {
  if (entry.startsWith("sw.js") || entry.startsWith("workbox-")) continue;
  files.push(entry);
}

// Compute revisions and build precache entries
const precacheEntries = [];
for (const file of files) {
  const data = await readFile(path.join(DIST, file));
  const revision = createHash("md5").update(data).digest("hex").slice(0, 8);
  precacheEntries.push({ url: file, revision });
}

const totalSize = (
  await Promise.all(files.map((f) => readFile(path.join(DIST, f))))
).reduce((sum, buf) => sum + buf.length, 0);

// Generate the service worker
const sw = `// Auto-generated by scripts/generate-sw.mjs — do not edit
const CACHE = "aura-v${CACHE_VERSION}";
const PRECACHE = ${JSON.stringify(precacheEntries, null, 0)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // Cache files individually so one failure doesn't block everything
      await Promise.all(
        PRECACHE.map(async (entry) => {
          try {
            const res = await fetch("/" + entry.url, { cache: "no-store" });
            if (res.ok) {
              await cache.put("/" + entry.url, res);
            }
          } catch (e) {
            // Skip failed files — they'll be cached on next visit
          }
        })
      );
      self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      // Delete old caches
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
      await self.clients.claim();
    })()
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);

      // Resolve directory index (e.g., /articles/ → /articles/index.html)
      let cacheKey = url.pathname;
      if (cacheKey.endsWith("/")) {
        cacheKey = cacheKey + "index.html";
      } else {
        // Check if the URL has a file extension (last segment contains a dot)
        const lastSlash = cacheKey.lastIndexOf("/");
        const lastSegment = cacheKey.slice(lastSlash + 1);
        if (!lastSegment.includes(".")) {
          cacheKey = cacheKey + "/index.html";
        }
      }

      // Try cache first (cache-first strategy)
      const cached = await cache.match(cacheKey);
      if (cached) return cached;

      // Also try the raw pathname (without index.html)
      const cachedRaw = await cache.match(url.pathname);
      if (cachedRaw) return cachedRaw;

      // Try network
      try {
        const res = await fetch(req);
        if (res.ok && res.type === "basic") {
          cache.put(url.pathname, res.clone());
        }
        return res;
      } catch (e) {
        // Offline fallback for navigation requests
        if (req.mode === "navigate") {
          const fallback = await cache.match("/index.html");
          if (fallback) return fallback;
        }
        return new Response("Offline", { status: 503, statusText: "Offline" });
      }
    })()
  );
});
`;

import { writeFile } from "node:fs/promises";
await writeFile(path.join(DIST, "sw.js"), sw);

console.log(
  `[generate-sw] Self-contained SW: ${precacheEntries.length} files (${(totalSize / 1024 / 1024).toFixed(2)} MB)`
);
